### ISSUE TITLE
Error on click in Documents List combobox

### ISSUE THREAD

**Issue by poloab** [dockpanelsuite/dockpanelsuite#445] opened 2016-11-20 00:52 UTC
Hi I'am adding a dockPanel and then some Forms as document content to my app, but when a click on the arrow with the list of documents, I get this error:

System.ArgumentOutOfRangeException: Index was outside the bounds of the array.
   en System.Runtime.InteropServices.Marshal.CopyToNative(Object source, Int32 startIndex, IntPtr destination, Int32 length)
   en System.Runtime.InteropServices.Marshal.Copy(Byte[] source, Int32 startIndex, IntPtr destination, Int32 length)
   en System.Drawing.Icon.BmpFrame()
   en System.Drawing.Icon.ToBitmap()
   en WeifenLuo.WinFormsUI.ThemeVS2013.VS2013DockPaneStrip.WindowList_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Can you help me?

**Comment by lextm** [comment] 2016-11-20 03:12
Which version of DockPanel Suite do you use?

**Comment by lextm** [comment] 2016-11-20 13:50
I cannot reproduce this issue with our sample project. You have to provide more details or I will close it in a few days.

**Closed** 2016-11-28 07:22 UTC
Labels: cannot reproduce
