### ISSUE TITLE
index out of range on DockContent.Hide()

### ISSUE THREAD

**Issue by yevgrig** [dockpanelsuite/dockpanelsuite#310] opened 2015-09-04 15:16 UTC
we are using DockPanel 2.9.0.0 with .net 3.5 SP1 on Windows 7 machines

DockContent d is shown in DockPanel p as follows

```c#
d.Show(p, DockState.Document);
```

DockContent needs to be hidden occasionally. We are hiding as follows:

```c#
p.SuspsendLayout(true);
d.Hide();
p.ResumeLayout(true, true);
```

We are observing an intermittent exception after this in the wild. Unable to recreate so far.
Thank you.

  System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at WeifenLuo.WinFormsUI.Docking.DockContentCollection.GetVisibleContent(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.TabCollection.get_Item(Int32 index)
   at WeifenLuo.WinFormsUI.Docking.VS2005DockPaneStrip.EnsureDocumentTabVisible(IDockContent content, Boolean repaint)
   at WeifenLuo.WinFormsUI.Docking.VS2005DockPaneStrip.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintTransparentBackground(PaintEventArgs e, Rectangle rectangle, Region transparentRegion)
   at System.Windows.Forms.Control.PaintTransparentBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.OnPaintBackground(PaintEventArgs pevent)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer, Boolean disposeEventArgs)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by roken** [comment] 2015-09-08 23:30
This is a duplicate of a longstanding issue: #209

Please feel free to add any additional insight to that item.

**Closed by roken** 2015-09-08 23:30 UTC
